import{a as q,S as M,i as n}from"./assets/vendor-S2qh7U4E.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const P="56897877-369a2b1f62c21f25620e74b5c",$="https://pixabay.com/api/";async function m(o,r=1){return(await q.get($,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const h=document.querySelector(".gallery"),y=document.querySelector("#loader"),p=document.querySelector("#load-more"),B=new M(".gallery a");function g(o){const r=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:t,views:i,comments:S,downloads:v})=>`
   <li class="photo-card">
        <a href="${c}">
            <img src="${s}" alt="${e}">
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><br>${t}</p>
          <p class="info-item"><b>Views</b><br>${i}</p>
          <p class="info-item"><b>Comments</b><br>${S}</p>
          <p class="info-item"><b>Downloads</b><br>${v}</p>
        </div>
    </li>
    `).join("");h.insertAdjacentHTML("beforeend",r),B.refresh()}function O(){h.innerHTML=""}function b(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}function w(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const x=document.querySelector(".form"),u=document.querySelector("#load-more");let a=1,l="",f=0;x.addEventListener("submit",E);u.addEventListener("click",A);async function E(o){if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),a=1,!l){n.error({message:"Please enter a search query!"});return}O(),d(),b();try{const r=await m(l,a);if(r.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}f=Math.ceil(r.totalHits/15),g(r.hits),a<f?w():(d(),n.info({message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.error(r),n.error({message:"Something went wrong!"})}finally{L()}}async function A(){a+=1,d(),b(),u.disabled=!0;try{const o=await m(l,a);g(o.hits),a<f?w():(d(),n.info({message:"We're sorry, but you've reached the end of search results."}));const s=document.querySelector(".photo-card").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}catch(o){console.error(o),n.error({message:"Something went wrong!"})}finally{u.disabled=!1,L()}}
//# sourceMappingURL=index.js.map
