import{a as S,S as q,i as a}from"./assets/vendor-S2qh7U4E.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const v="56897877-369a2b1f62c21f25620e74b5c",M="https://pixabay.com/api/";async function m(o,r=1){return(await S.get(M,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const h=document.querySelector(".gallery"),p=document.querySelector("#loader"),g=document.querySelector("#load-more"),P=new q(".gallery a");function y(o){const r=o.map(({webformatURL:s,largeImageURL:c,tags:e,likes:t,views:i,comments:L,downloads:w})=>`
   <li class="photo-card">
        <a href="${c}">
            <img src="${s}" alt="${e}">
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><br>${t}</p>
          <p class="info-item"><b>Views</b><br>${i}</p>
          <p class="info-item"><b>Comments</b><br>${L}</p>
          <p class="info-item"><b>Downloads</b><br>${w}</p>
        </div>
    </li>
    `).join("");h.insertAdjacentHTML("beforeend",r),P.refresh()}function $(){h.innerHTML=""}function B(){p.classList.remove("hidden")}function O(){p.classList.add("hidden")}function b(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}const x=document.querySelector(".form"),u=document.querySelector("#load-more");let n=1,l="",f=0;x.addEventListener("submit",E);u.addEventListener("click",A);function E(o){if(o.preventDefault(),console.log("Submit works"),l=o.currentTarget.elements["search-text"].value.trim(),n=1,!l){a.error({message:"Please enter a search query!"});return}$(),d(),B(),m(l,n).then(r=>{if(r.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}f=Math.ceil(r.totalHits/15),y(r.hits),n<f?b():d()}).catch(r=>{console.error(r),a.error({message:"Something went wrong!"})}).finally(()=>{O()})}async function A(){n+=1,u.disabled=!0;try{const o=await m(l,n);y(o.hits),n<f?b():(d(),a.info({message:"We're sorry, but you've reached the end of search results."}));const s=document.querySelector(".photo-card").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}catch(o){console.error(o),a.error({message:"Something went wrong!"})}finally{u.disabled=!1}}
//# sourceMappingURL=index.js.map
